name: Continuos Integration
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**', '!update/**', '!pr/**']

jobs:

  test-action-itself:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: test-gh-action
        with:
          files: 'resources/ci_test_file.scala_test,resources/ci_test_file2.scala_test'
      - name: Check on failures
        run: |
          echo "Result: ${{ steps.test-gh-action.outputs.result }}"
          echo "log: ${{ steps.test-gh-action.outputs.log }}"
          if [ ${{ steps.test-gh-action.outputs.result }} == 'false' ]; then
            echo "Test failed"
            exit 1
          else
            echo "Test passed"
            exit 0
          fi

  run-scala-cli-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: VirtusLab/scala-cli-setup@main
      - name: Run tests
        run: scala-cli test .